version: '3.7'
services:
  nginx:
   container_name: ysu-addin-backend
   image: nginx:1.19.6
   restart: always
   ports:
   - 80:80
   - 443:443
   volumes:
   - ./nginx/conf.d:/etc/nginx/conf.d
   - ./certs:/etc/nginx/certs
   depends_on:
   - app
  
  app:
    restart: always
    build: ./app
    working_dir: /app
    volumes:
      - ./app:/app
    expose:
      - "8080"
      - "8433"
    command: mvn clean spring-boot:run